"""
=============================================================================
finetune.py — Supervised Fine-Tuning on Instructions (Phase 2)
=============================================================================

Takes the pre-trained model from Phase 1 (train.py) and fine-tunes it on
instruction/response pairs. This teaches the model to follow instructions
rather than just predict the next token in raw text.

Pipeline:
  1. Load the pre-trained checkpoint from Phase 1
  2. Load instruction dataset (Alpaca — 52K instruction/response pairs)
  3. Fine-tune with a lower learning rate (2e-5 vs 3e-4 in pre-training)
     to avoid destroying the language knowledge learned in Phase 1
  4. Save the fine-tuned model

Key differences from pre-training:
  - Much lower learning rate (preserves pre-trained knowledge)
  - Structured data (instruction/response pairs instead of raw text)
  - Fewer steps needed (the model already understands language)

Usage:
    python3 finetune.py

Input:
    checkpoints/model_final.pt — pre-trained model from train.py

Output:
    checkpoints/model_finetuned.pt — instruction-tuned model

=============================================================================
"""

import os
import torch
from torch.utils.data import DataLoader
from tqdm import tqdm
from datasets import load_dataset

from config import ModelConfig, TrainConfig
from model import GPTModel
from dataset import get_tokenizer, InstructDataset


def finetune(checkpoint_path: str = "checkpoints/model_final.pt"):
    # =========================================================================
    # Setup: Configure for fine-tuning (lower LR, fewer steps)
    # =========================================================================
    mcfg = ModelConfig()
    tcfg = TrainConfig()
    tcfg.learning_rate = 2e-5   # 15x lower than pre-training to preserve knowledge
    tcfg.max_steps = 2000       # Fewer steps needed for fine-tuning

    # Device selection: CUDA > MPS > CPU
    device = "cuda" if torch.cuda.is_available() else ("mps" if torch.backends.mps.is_available() else "cpu")

    tokenizer = get_tokenizer()
    mcfg.vocab_size = len(tokenizer)

    # =========================================================================
    # Step 1: Load pre-trained model
    # =========================================================================
    # Start from the pre-trained weights — don't train from scratch!
    model = GPTModel(mcfg).to(device)
    if os.path.exists(checkpoint_path):
        model.load_state_dict(torch.load(checkpoint_path, map_location=device))
        print(f"Loaded checkpoint: {checkpoint_path}")

    # =========================================================================
    # Step 2: Load instruction dataset
    # =========================================================================
    # Alpaca: 52K instruction/response pairs generated by GPT-4.
    # Using first 5000 for faster training on small models.
    print("Loading instruction dataset...")
    raw = load_dataset("tatsu-lab/alpaca", split="train[:5000]")
    examples = [{"instruction": r["instruction"], "response": r["output"]} for r in raw]

    dataset = InstructDataset(examples, tokenizer, max_len=mcfg.max_seq_len)
    loader = DataLoader(dataset, batch_size=tcfg.batch_size, shuffle=True, drop_last=True)

    # =========================================================================
    # Step 3: Fine-tuning loop
    # =========================================================================
    # Simpler than pre-training — no gradient accumulation needed for small datasets
    optimizer = torch.optim.AdamW(model.parameters(), lr=tcfg.learning_rate)
    model.train()
    step = 0

    for epoch in range(50):
        for input_ids, targets in tqdm(loader, desc=f"FT Epoch {epoch}"):
            input_ids, targets = input_ids.to(device), targets.to(device)

            # Forward pass and compute loss
            _, loss = model(input_ids, targets)
            loss.backward()

            # Clip gradients and update weights
            torch.nn.utils.clip_grad_norm_(model.parameters(), tcfg.max_grad_norm)
            optimizer.step()
            optimizer.zero_grad()

            # Log progress
            if step % 100 == 0:
                print(f"Step {step} | Loss: {loss.item():.4f}")

            step += 1
            if step >= tcfg.max_steps:
                break
        if step >= tcfg.max_steps:
            break

    # =========================================================================
    # Step 4: Save fine-tuned model
    # =========================================================================
    save_path = os.path.join(tcfg.output_dir, "model_finetuned.pt")
    torch.save(model.state_dict(), save_path)
    print(f"Fine-tuned model saved to {save_path}")


if __name__ == "__main__":
    finetune()
